# Generated by Django 3.0.5 on 2020-07-06 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200706_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='', max_length=30, null=True, unique=True),
        ),
    ]
